project/__init__.py
from flask import Flask, render_template


######################################
#### Application Factory Function ####
######################################

def create_app():
    # Create the Flask application
    app = Flask(__name__)

    register_blueprints(app)
    register_error_pages(app)
    return app


########################
### Helper Functions ###
########################

def register_blueprints(app):
    # Import the blueprints
    from project.books import books_blueprint
    from project.blog import blog_blueprint

    # Since the application instance is now created, register each Blueprint
    # with the Flask application instance (app)
    app.register_blueprint(books_blueprint)
    app.register_blueprint(blog_blueprint)


def register_error_pages(app):
    @app.errorhandler(404)
    def page_not_found(e):
        return render_template('404.html'), 404

project/blog/__init__.py
"""
The `blog` blueprint handles displaying blog posts.
"""
from flask import Blueprint

blog_blueprint = Blueprint('blog', __name__, template_folder='templates')

from . import routes

project/blog/routes.py
from . import blog_blueprint
from flask import render_template, abort


blog_post_titles = ['kitchenaid_mixer', 'measuring_cups', 'air_fryer']


@blog_blueprint.route('/blog/')
def blog():
    return render_template('blog/blog.html')


@blog_blueprint.route('/blog/<blog_title>/')
def posts(blog_title):
    if blog_title not in blog_post_titles:
        abort(404)

    return render_template(f'blog/{blog_title}.html')


@blog_blueprint.route('/about/')
def about():
    return render_template('blog/about.html')

project/books/__init__.py
"""
The `books` blueprint handles displaying recipes.
"""
from flask import Blueprint

books_blueprint = Blueprint('books', __name__, template_folder='templates')

from . import routes

project/books/routes.py
from . import books_blueprint
from flask import render_template, abort


torah = ['Genesis', 'Exodus', 'Leviticus', 'Numbers','Deuteronomy']
neviim = ['Joshua', 'Judges', 'Samuel', 'Kings', 'Isaiah' , 'Jeremiah', 'Ezekiel',
            'Hosea', 'Joel', 'Amos', 'Obadiah', 'Jonah', 'Micah' , 'Nahum', 
            'Habakkuk', 'Zephaniah', 'Haggai', 'Zechariah', 'Malachi']
baked_goods_recipes_names = ['bagels', 'french_bread', 'pitas', 'irish_soda_bread']
side_dishes_recipes_names = ['sweet_potatoes', 'spanish_rice', 'jasmine_rice']
dessert_recipes_names = ['brownies', 'chocolate_chip_cookies', 'linzer_cookies', 'sugar_cookies']
smoothies_recipes_names = ['berry_smoothie', 'chocolate_milk_shake']


@books_blueprint.route('/')
def books():
    return render_template('books/books.html')


@books_blueprint.route('/torah/')
def torah_books():
    return render_template('books/torah.html')


@books_blueprint.route('/torah/<book_name>/')
def torah_book(book_name):
    if book_name not in torah:
        abort(404)

    return render_template(f'torah/{book_name}.html')


@books_blueprint.route('/neviim/')
def neviim_books():
    return render_template('books/Neviim.html')


@books_blueprint.route('/neviim/<book_name>/')
def neviim_book(book_name):
    if book_name not in neviim:
        abort(404)

    return render_template(f'neviim/{book_name}.html')


@books_blueprint.route('/baked_goods/')
def baked_goods_recipes():
    return render_template('books/baked_goods.html')


@books_blueprint.route('/baked_goods/<book_name>/')
def baked_goods_recipe(book_name):
    if book_name not in baked_goods_recipes_names:
        abort(404)

    return render_template(f'books/{book_name}.html')


@books_blueprint.route('/side_dishes/')
def side_dishes_recipes():
    return render_template('books/side_dishes.html')


@books_blueprint.route('/side_dishes/<book_name>/')
def side_dishes_recipe(book_name):
    if book_name not in side_dishes_recipes_names:
        abort(404)

    return render_template(f'books/{book_name}.html')


@books_blueprint.route('/dessert/')
def dessert_recipes():
    return render_template('books/dessert.html')


@books_blueprint.route('/dessert/<book_name>/')
def dessert_recipe(book_name):
    if book_name not in dessert_recipes_names:
        abort(404)

    return render_template(f'books/{book_name}.html')


@books_blueprint.route('/smoothies/')
def smoothies_recipes():
    return render_template('books/smoothies.html')


@books_blueprint.route('/smoothies/<book_name>/')
def smoothies_recipe(book_name):
    if book_name not in smoothies_recipes_names:
        abort(404)

    return render_template(f'books/{book_name}.html')

project/templates/base.html
<!DOCTYPE html>
<html lang="en">
    <head>
        <!-- Required meta tags -->
        <meta charset="utf-8">
        <meta name="viewport" content="width=device-width, initial-scale=1, shrink-to-fit=no">
        <title>Read Scripture</title>

        <!-- Local CSS file for styling the application-->
        <link rel="stylesheet" href="{{ url_for('static', filename='css/base_style.css') }}">

        <!-- Additional Styling -->
        {% block styling %}
        {% endblock %}
    </head>

    <body>
        <header>
            <h1>Read Scripture Daily</h1>
            <nav>
                <ul>
                    <li class="nav__item"><a href="{{ url_for('books.books') }}" class="nav__link">Books</a></li>
                    <li class="nav__item"><a href="{{ url_for('blog.blog') }}" class="nav__link">Blog</a></li>
                    <li class="nav__item"><a href="{{ url_for('blog.about') }}" class="nav__link">About</a></li>
                </ul>
            </nav>
        </header>

        <main class="content">
            <!-- child template -->
            {% block content %}
            {% endblock %}
        </main>

        <footer>
            <p>Glory to the Lord!</p>
        </footer>
    </body>
</html>

project/templates/blogpost.html
{% extends "base.html" %}

{% block styling %}
<link rel="stylesheet" href="{{ url_for('static', filename='css/blogpost_style.css') }}">
{% endblock %}

{% block content %}
<div class="blogpost-container card-overlay">
    <div class="blogpost__heading">
        {% block title %}
        {% endblock %}

        <h3>by Patrick Kennedy</h3>

        {% block date %}
        {% endblock %}
    </div>

    <div class="blogpost__image">
        {% block image %}
        {% endblock %}
    </div>

    <div class="blogpost__article">
        {% block article %}
        {% endblock %}
    </div>
</div>
{% endblock %}

project/templates/books.html
{% extends "base.html" %}

{% block styling %}
<link rel="stylesheet" href="{{ url_for('static', filename='css/recipe_style.css') }}">
{% endblock %}

{% block content %}
<div class="recipe-detail-container">
    <div class="recipe-title">
        {% block recipe_title %}
        {% endblock %}
    </div>

    <div class="recipe-description card-overlay">
        {% block recipe_description %}
        {% endblock %}
    </div>

    <div class="recipe-image">
        {% block recipe_image %}
        {% endblock %}
    </div>

    <div class="recipe-tips card-overlay">
        {% block recipe_tips %}
        {% endblock %}
    </div>

    <div class="recipe-ingredients card-overlay">
        {% block recipe_ingredients %}
        {% endblock %}
    </div>

    <div class="recipe-steps card-overlay">
        {% block recipe_steps %}
        {% endblock %}
    </div>
</div>
{% endblock %}

project/templates/recipe.html
{% extends "base.html" %}

{% block styling %}
<link rel="stylesheet" href="{{ url_for('static', filename='css/recipe_style.css') }}">
{% endblock %}

{% block content %}
<div class="recipe-detail-container">
    <div class="recipe-title">
        {% block recipe_title %}
        {% endblock %}
    </div>

    <div class="recipe-description card-overlay">
        {% block recipe_description %}
        {% endblock %}
    </div>

    <div class="recipe-image">
        {% block recipe_image %}
        {% endblock %}
    </div>

    <div class="recipe-tips card-overlay">
        {% block recipe_tips %}
        {% endblock %}
    </div>

    <div class="recipe-ingredients card-overlay">
        {% block recipe_ingredients %}
        {% endblock %}
    </div>

    <div class="recipe-steps card-overlay">
        {% block recipe_steps %}
        {% endblock %}
    </div>
</div>
{% endblock %}