project/books/__init__.py
"""
The `books` blueprint handles displaying recipes.
"""
from flask import Blueprint

books_blueprint = Blueprint('books', __name__, template_folder='templates')

from . import routes

project/books/routes.py
from . import books_blueprint
from flask import render_template, abort


torah = ['Genesis', 'Exodus', 'Leviticus', 'Numbers','Deuteronomy']
neviim = ['Joshua', 'Judges', 'Samuel', 'Kings', 'Isaiah' , 'Jeremiah', 'Ezekiel',
            'Hosea', 'Joel', 'Amos', 'Obadiah', 'Jonah', 'Micah' , 'Nahum', 
            'Habakkuk', 'Zephaniah', 'Haggai', 'Zechariah', 'Malachi']
baked_goods_recipes_names = ['bagels', 'french_bread', 'pitas', 'irish_soda_bread']
side_dishes_recipes_names = ['sweet_potatoes', 'spanish_rice', 'jasmine_rice']
dessert_recipes_names = ['brownies', 'chocolate_chip_cookies', 'linzer_cookies', 'sugar_cookies']
smoothies_recipes_names = ['berry_smoothie', 'chocolate_milk_shake']


@books_blueprint.route('/')
def books():
    return render_template('books/books.html')


@books_blueprint.route('/torah/')
def torah_books():
    return render_template('books/torah.html')


@books_blueprint.route('/torah/<book_name>/')
def torah_book(book_name):
    if book_name not in torah:
        abort(404)

    return render_template(f'torah/{book_name}.html')


@books_blueprint.route('/neviim/')
def neviim_books():
    return render_template('books/Neviim.html')


@books_blueprint.route('/neviim/<book_name>/')
def neviim_book(book_name):
    if book_name not in neviim:
        abort(404)

    return render_template(f'neviim/{book_name}.html')


@books_blueprint.route('/baked_goods/')
def baked_goods_recipes():
    return render_template('books/baked_goods.html')


@books_blueprint.route('/baked_goods/<book_name>/')
def baked_goods_recipe(book_name):
    if book_name not in baked_goods_recipes_names:
        abort(404)

    return render_template(f'books/{book_name}.html')


@books_blueprint.route('/side_dishes/')
def side_dishes_recipes():
    return render_template('books/side_dishes.html')


@books_blueprint.route('/side_dishes/<book_name>/')
def side_dishes_recipe(book_name):
    if book_name not in side_dishes_recipes_names:
        abort(404)

    return render_template(f'books/{book_name}.html')


@books_blueprint.route('/dessert/')
def dessert_recipes():
    return render_template('books/dessert.html')


@books_blueprint.route('/dessert/<book_name>/')
def dessert_recipe(book_name):
    if book_name not in dessert_recipes_names:
        abort(404)

    return render_template(f'books/{book_name}.html')


@books_blueprint.route('/smoothies/')
def smoothies_recipes():
    return render_template('books/smoothies.html')


@books_blueprint.route('/smoothies/<book_name>/')
def smoothies_recipe(book_name):
    if book_name not in smoothies_recipes_names:
        abort(404)

    return render_template(f'books/{book_name}.html')

project/books/templates/books/Neviim.html
{% extends "base.html" %}

{% block content %}
<h1 class="section-title">Former Prophets</h1>
<div class="recipe-container">

    <div class="card">
        <a href="{{ url_for('books.neviim_book', book_name='Joshua') }}">
            <img
              src="{{ url_for('static', filename='img/Joshua.jpg') }}"
              alt="Joshua"
              class="card__image" />
            <div class="card__body">
                <h2>Joshua</h2>
                <p class="recipe-badge dairy-free-badge">Dairy-Free</p>
                <p class="recipe-badge soy-free-badge">Soy-Free</p>
            </div>
        </a>
    </div>

    <div class="card">
        <a href="{{ url_for('books.neviim_book', book_name='Judges') }}">
            <img
              src="{{ url_for('static', filename='img/Judges.jpg') }}"
              alt="Judges"
              class="card__image" />
            <div class="card__body">
                <h2>Judges</h2>
                <p class="recipe-badge dairy-free-badge">Dairy-Free</p>
                <p class="recipe-badge soy-free-badge">Soy-Free</p>
            </div>
        </a>
    </div>

    <div class="card">
        <a href="{{ url_for('books.neviim_book', book_name='Samuel') }}">
            <img
              src="{{ url_for('static', filename='img/Samuel.jpg') }}"
              alt="Samuel"
              class="card__image" />
            <div class="card__body">
                <h2>Samuel</h2>
                <p class="recipe-badge soy-free-badge">Soy-Free</p>
            </div>
        </a>
    </div>

    <div class="card">
        <a href="{{ url_for('books.neviim_book', book_name='Kings') }}">
            <img
              src="{{ url_for('static', filename='img/Kings.jpg') }}"
              alt="Kings"
              class="card__image" />
            <div class="card__body">
                <h2 class="recipe-title-long">Kings</h2>
                <p class="recipe-badge dairy-free-badge">Dairy-Free</p>
                <p class="recipe-badge soy-free-badge">Soy-Free</p>
            </div>
        </a>
    </div>

    

</div>

<h1 class="section-title">Latter Prophets</h1>
<div class="recipe-container">

    <div class="card">
        <a href="{{ url_for('books.neviim_book', book_name='Isaiah') }}">
            <img
              src="{{ url_for('static', filename='img/Isaiah.jpg') }}"
              alt="Isaiah"
              class="card__image" />
            <div class="card__body">
                <h2>Isaiah</h2>
                <p class="recipe-badge dairy-free-badge">Dairy-Free</p>
                <p class="recipe-badge soy-free-badge">Soy-Free</p>
            </div>
        </a>
    </div>

    <div class="card">
        <a href="{{ url_for('books.neviim_book', book_name='Jeremiah') }}">
            <img
              src="{{ url_for('static', filename='img/Jeremiah.jpg') }}"
              alt="Jeremiah"
              class="card__image" />
            <div class="card__body">
                <h2>Jeremiah</h2>
                <p class="recipe-badge dairy-free-badge">Dairy-Free</p>
                <p class="recipe-badge soy-free-badge">Soy-Free</p>
            </div>
        </a>
    </div>

    <div class="card">
        <a href="{{ url_for('books.neviim_book', book_name='Ezekiel') }}">
            <img
              src="{{ url_for('static', filename='img/Ezekiel.jpg') }}"
              alt="Ezekiel"
              class="card__image" />
            <div class="card__body">
                <h2>Ezekiel</h2>
                <p class="recipe-badge dairy-free-badge">Dairy-Free</p>
                <p class="recipe-badge soy-free-badge">Soy-Free</p>
            </div>
        </a>
    </div>

</div>

<h1 class="section-title">Minor Prophets</h1>
<div class="recipe-container">

    <div class="card">
        <a href="{{ url_for('books.neviim_book', book_name='Hosea') }}">
            <img
              src="{{ url_for('static', filename='img/Hosea.jpg') }}"
              alt="Hosea"
              class="card__image" />
            <div class="card__body">
                <h2>Hosea</h2>
                <p class="recipe-badge dairy-free-badge">Dairy-Free</p>
                <p class="recipe-badge soy-free-badge">Soy-Free</p>
            </div>
        </a>
    </div>

    <div class="card">
        <a href="{{ url_for('books.neviim_book', book_name='Joel') }}">
            <img
              src="{{ url_for('static', filename='img/Joel.jpg') }}"
              alt="Joel"
              class="card__image" />
            <div class="card__body">
                <h2>Joel</h2>
                <p class="recipe-badge dairy-free-badge">Dairy-Free</p>
                <p class="recipe-badge soy-free-badge">Soy-Free</p>
            </div>
        </a>
    </div>

    <div class="card">
        <a href="{{ url_for('books.neviim_book', book_name='Amos') }}">
            <img
              src="{{ url_for('static', filename='img/Amos.jpg') }}"
              alt="Amos"
              class="card__image" />
            <div class="card__body">
                <h2>Amos</h2>
                <p class="recipe-badge dairy-free-badge">Dairy-Free</p>
                <p class="recipe-badge soy-free-badge">Soy-Free</p>
            </div>
        </a>
    </div>

    <div class="card">
        <a href="{{ url_for('books.neviim_book', book_name='Obadiah') }}">
            <img
              src="{{ url_for('static', filename='img/Obadiah.jpg') }}"
              alt="Obadiah"
              class="card__image" />
            <div class="card__body">
                <h2>Obadiah</h2>
                <p class="recipe-badge dairy-free-badge">Dairy-Free</p>
                <p class="recipe-badge soy-free-badge">Soy-Free</p>
            </div>
        </a>
    </div>

    <div class="card">
        <a href="{{ url_for('books.neviim_book', book_name='Jonah') }}">
            <img
              src="{{ url_for('static', filename='img/Jonah.jpg') }}"
              alt="Jonah"
              class="card__image" />
            <div class="card__body">
                <h2>Jonah</h2>
                <p class="recipe-badge dairy-free-badge">Dairy-Free</p>
                <p class="recipe-badge soy-free-badge">Soy-Free</p>
            </div>
        </a>
    </div>

    <div class="card">
        <a href="{{ url_for('books.neviim_book', book_name='Micah') }}">
            <img
              src="{{ url_for('static', filename='img/Micah.jpg') }}"
              alt="Micah"
              class="card__image" />
            <div class="card__body">
                <h2>Micah</h2>
                <p class="recipe-badge dairy-free-badge">Dairy-Free</p>
                <p class="recipe-badge soy-free-badge">Soy-Free</p>
            </div>
        </a>
    </div>

    <div class="card">
        <a href="{{ url_for('books.neviim_book', book_name='Nahum') }}">
            <img
              src="{{ url_for('static', filename='img/Nahum.png') }}"
              alt="Nahum"
              class="card__image" />
            <div class="card__body">
                <h2>Nahum</h2>
                <p class="recipe-badge dairy-free-badge">Dairy-Free</p>
                <p class="recipe-badge soy-free-badge">Soy-Free</p>
            </div>
        </a>
    </div>

    <div class="card">
        <a href="{{ url_for('books.neviim_book', book_name='Habakkuk') }}">
            <img
              src="{{ url_for('static', filename='img/Habakkuk.jpg') }}"
              alt="Habakkuk"
              class="card__image" />
            <div class="card__body">
                <h2>Habakkuk</h2>
                <p class="recipe-badge dairy-free-badge">Dairy-Free</p>
                <p class="recipe-badge soy-free-badge">Soy-Free</p>
            </div>
        </a>
    </div>

    <div class="card">
        <a href="{{ url_for('books.neviim_book', book_name='Zephaniah') }}">
            <img
              src="{{ url_for('static', filename='img/Zephaniah.jpg') }}"
              alt="Zephaniah"
              class="card__image" />
            <div class="card__body">
                <h2>Zephaniah</h2>
                <p class="recipe-badge dairy-free-badge">Dairy-Free</p>
                <p class="recipe-badge soy-free-badge">Soy-Free</p>
            </div>
        </a>
    </div>

    <div class="card">
        <a href="{{ url_for('books.neviim_book', book_name='Haggai') }}">
            <img
              src="{{ url_for('static', filename='img/Haggai.jpg') }}"
              alt="Haggai"
              class="card__image" />
            <div class="card__body">
                <h2>Haggai</h2>
                <p class="recipe-badge dairy-free-badge">Dairy-Free</p>
                <p class="recipe-badge soy-free-badge">Soy-Free</p>
            </div>
        </a>
    </div>

    <div class="card">
        <a href="{{ url_for('books.neviim_book', book_name='Zechariah') }}">
            <img
              src="{{ url_for('static', filename='img/Zechariah.jpg') }}"
              alt="Zechariah"
              class="card__image" />
            <div class="card__body">
                <h2>Zechariah</h2>
                <p class="recipe-badge dairy-free-badge">Dairy-Free</p>
                <p class="recipe-badge soy-free-badge">Soy-Free</p>
            </div>
        </a>
    </div>

    <div class="card">
        <a href="{{ url_for('books.neviim_book', book_name='Malachi') }}">
            <img
              src="{{ url_for('static', filename='img/Malachi.jpg') }}"
              alt="Malachi"
              class="card__image" />
            <div class="card__body">
                <h2>Malachi</h2>
                <p class="recipe-badge dairy-free-badge">Dairy-Free</p>
                <p class="recipe-badge soy-free-badge">Soy-Free</p>
            </div>
        </a>
    </div>

</div>
{% endblock %}

project/books/templates/books/bagels.html
{% extends "books.html" %}

{% block recipe_title %}
<h1>Bagels</h1>
{% endblock %}

{% block recipe_description %}
<h2>Description</h2>
<p>Homemade bagels that are fresh out of the oven are delicious! Once you get the technique down, they are relatively easy to make.</p>
<p>During quarantine (2020), we stopped going to our grocery store to pick up fresh bagels in the mornings. After a few months, I decided to try making bagels at home. I could not believe how much I missed bagels!</p>
<p>Bagels are delicious by themselves, but I especially like them with peanut butter and jelly or as a breakfast sandwich (with scrambled eggs and bacon)!</p>
{% endblock %}

{% block recipe_image %}
<img src="{{ url_for('static', filename='img/bagels.jpg') }}"  alt="Bagels" />
{% endblock %}

{% block recipe_tips %}
<h2>Tips</h2>
<p>When making the hole in the bagels, use your thumb to press a hole through the center of the dough ball and then use your index fingers to stretch out the dough to make the hole about 1" in diameter.</p>
<p>It may seem that the dough is to wet when it comes out of the boiling water, but this is good.  The moisture on the dough makes for a crunchy exterior while keeping the interior nice and soft.</p>
<p>The water needs to be between 100-110 degrees (Fahrenheit) to active the yeast; I use a thermometer to check the water temperature. The sugar also helps the yeast bloom.</p>
<p>Make sure to thoroughly combine the salt into the flour; salt can kill the yeast if applied directly to the yeast.</p>
{% endblock %}

{% block recipe_ingredients %}
<h2>List of Ingredients</h2>
<ul>
    <li>500 grams of Bread Flour</li>
    <li>1.5 Tablespoons of Sugar</li>
    <li>1 Packet (10g) of Instant Dry Yeast</li>
    <li>320 mL Water (between 100-100 degrees (Fahrenheit))</li>
    <li>1.5 Teaspoons of Salt</li>
    <li>0.5 Tablespoons of Canola Oil</li>
</ul>
{% endblock %}

{% block recipe_steps %}
<h2>Recipe Steps</h2>
<ol>
    <li>Pour the yeast into the bowl of a stand mixer; Add the water and sugar to bloom the yeast.</li>
    <li>Measure out the flour and salt into a separate bowl and combine thoroughly.</li>
    <li>Knead all the ingredients in a stand mixer for 5-10 minutes. The dough should come together with almost no dough sticking to the sides of the bowl.</li>
    <li>Transfer the dough (using a spatchula) onto a clean surface and knead into a smooth ball of dough.</li>
    <li>In a new bowl, spray the Canola oil on the bottom and sides to prevent the dough from sticking during the rise time.</li>
    <li>Place the dough ball into the new bowl and cover tightly with sticky wrap.</li>
    <li>Place the bowl in a warm spot in the kitchen to let rise for 1-2 hours. The dough should double in size during this time.</li>
    <li>Transfer the dough onto a clean surface and divide into 8 pieces.</li>
    <li>Form each dough piece into a little ball and let rest on baking sheet (no parchment paper is needed).</li>
    <li>Bring a large pot of water to a gentle boil.</li>
    <li>Preheat the oven to 425 degrees (F).</li>
    <li>Use your thumb to make a hole in the center of each dough ball and then use your index fingers to stretch out the dough to have the hole be 1" in diameter.</li>
    <li>Once the water is boiling, place each bagel into the boiling water. You'll need to do this multiple batches to prevent crowding the pot.</li>
    <li>Boil for 1 minute on each side and then return the bagels to the baking sheet.</li>
    <li>When the bagels are wet, place any toppings on the bagels (like sesame seeds).</li>
    <li>Bake for 20 minutes at 425 degrees (F).</li>
    <li>Let the bagels cool for 10 minutes before eating!</li>
</ol>
{% endblock %}

project/books/templates/books/brownies.html
{% extends "books.html" %}

{% block recipe_title %}
<h1>Brownies</h1>
{% endblock %}

{% block recipe_description %}
<h2>Description</h2>
<p>While there are a lot of great options for brownie mixes, this homemade recipe makes my favorite brownies.</p>
<p>For more inspiration about brownies, I recommend the <a href="https://www.youtube.com/watch?v=VvJm4pQZ04s">Best Brownies You'll Ever Eat</a> video on YouTube.  I don't follow this recipe, but the techniques shown are excellent.</p>
<p>This recipe makes chewy and fudgy brownies that are just the perfect texture.</p>
{% endblock %}

{% block recipe_image %}
<img src="{{ url_for('static', filename='img/brownies.jpg') }}"  alt="Brownies" />
{% endblock %}

{% block recipe_tips %}
<h2>Tips</h2>
<p>The <b>KEY STEP</b> to making brownies is using a hand mixer to mix the batter for 10 minutes.  It may feel like an eternity, but it's the key to fudgy and light brownies.</p>
<p>Add a pinch of sea salt to the top of the brownies to add a salty note with the chocolatey brownies.</p>
<p>Make sure to coat the pan with a generous amount of butter to try to prevent the brownies from sticking to the pan.</p>
<p>If you have problems with the brownies sticking to the pan, try slamming the pan upside-down onto a cutting board.</p>
{% endblock %}

{% block recipe_ingredients %}
<h2>List of Ingredients</h2>
<ul>
    <li>1/2 Cup of Dairy-Free Butter (recommendation: <a href="https://www.earthbalancenatural.com/spreads/soy-free-buttery-spread">Earth Balance - Soy Free Butter Spread</a>)</li>
    <li>1.25 Cups of Granulated Sugar</li>
    <li>3/4 Cup of Cocoa Powder</li>
    <li>1/2 Teaspoon of Salt</li>
    <li>1 Teaspoon of Vanilla Extract</li>
    <li>2 Large Eggs</li>
    <li>1/3 Cup of All-Purpose Flour</li>
    <li>Sea Salt (optional)</li>
</ul>
{% endblock %}

{% block recipe_steps %}
<h2>Recipe Steps</h2>
<ol>
    <li>Preheat the oven to 325 degrees (Fahrenheit)</li>
    <li>Spread a generous amount of dairy-free butter on the bottom and sides of an 8"x8" shallow pan</li>
    <li>In a large mixing bowl, combine all ingredients EXCEPT the flour</li>
    <li>Using a hand mixer, mix the batter for 10 minutes (important step!)</li>
    <li>Add the flour to the mixture and GENTLY fold in flour into the batter until just incorporated (to prevent over mixing the batter with the flour in it)</li>
    <li>Scrape the batter into the pan and even out with a spatula</li>
    <li>Bake for 25-30 minutes, checking with a toothpick (no batter when sticking it into the brownies) to see that the brownies are cooked all the way through</li>
    <li>(Optional) Halfway through the baking, add a pinch of sea salt to the top of the brownies</li>
    <li>Let the brownies cool for at least 15 minutes before enjoying!</li>
</ol>
{% endblock %}

project/books/templates/books/dessert.html
{% extends "base.html" %}

{% block content %}
<div class="recipe-container">

    <div class="card">
        <a href="{{ url_for('books.dessert_recipe', book_name='brownies') }}">
            <img
              src="{{ url_for('static', filename='img/brownies.jpg') }}"
              alt="Brownies"
              class="card__image" />
            <div class="card__body">
                <h2>Brownies</h2>
                <p class="recipe-badge dairy-free-badge">Dairy-Free</p>
                <p class="recipe-badge soy-free-badge">Soy-Free</p>
            </div>
        </a>
    </div>

    <div class="card">
        <a href="{{ url_for('books.dessert_recipe', book_name='chocolate_chip_cookies') }}">
            <img
              src="{{ url_for('static', filename='img/chocolate_chip_cookies.jpg') }}"
              alt="Chocolate Chip Cookies"
              class="card__image" />
            <div class="card__body">
                <h2 class="recipe-title-long">Chocolate Chip Cookies</h2>
                <p class="recipe-badge dairy-free-badge">Dairy-Free</p>
                <p class="recipe-badge soy-free-badge">Soy-Free</p>
            </div>
        </a>
    </div>

    <div class="card">
        <a href="{{ url_for('books.dessert_recipe', book_name='linzer_cookies') }}">
            <img
              src="{{ url_for('static', filename='img/linzer_cookies.jpg') }}"
              alt="Linzer Cookies"
              class="card__image" />
            <div class="card__body">
                <h2>Linzer Cookies</h2>
                <p class="recipe-badge dairy-free-badge">Dairy-Free</p>
                <p class="recipe-badge soy-free-badge">Soy-Free</p>
            </div>
        </a>
    </div>

    <div class="card">
        <a href="{{ url_for('books.dessert_recipe', book_name='sugar_cookies') }}">
            <img
              src="{{ url_for('static', filename='img/sugar_cookies.jpg') }}"
              alt="Sugar Cookies"
              class="card__image" />
            <div class="card__body">
                <h2>Sugar Cookies</h2>
                <p class="recipe-badge dairy-free-badge">Dairy-Free</p>
                <p class="recipe-badge soy-free-badge">Soy-Free</p>
            </div>
        </a>
    </div>

</div>
{% endblock %}

project/books/templates/books/omelette.html
{% extends "books.html" %}

{% block recipe_title %}
<h1>Omelette</h1>
{% endblock %}

{% block recipe_description %}
<h2>Description</h2>
<p>Omelettes are a delicious meal for breakfast or even for dinner!</p>
<p>You can add your favorite ingredients into an omelette to personalize it to your taste. I like sauteed bell peppers and spinach in my omelette.</p>
{% endblock %}

{% block recipe_image %}
<img src="{{ url_for('static', filename='img/omelette.jpg') }}"  alt="Omelette" />
{% endblock %}

{% block recipe_tips %}
<h2>Tips</h2>
<p>Use a generous amount of oil spray on the frying pan before pouring in the eggs to prevent the eggs from sticking when forming the omelette.</p>
<p>Add in the ingredients (veggies, meat, etc.) to the eggs when the eggs are still runny to keep the ingredients inside the omelette.</p>
{% endblock %}

{% block recipe_ingredients %}
<h2>List of Ingredients</h2>
<ul>
    <li>2 or 3 Large Eggs</li>
    <li>1/2 Teaspoon of Salt</li>
    <li>1/2 Teaspoon of Black Pepper</li>
    <li>Canola Oil Spray</li>
    <li>1/2 of a Bell Pepper (diced into small pieces)</li>
    <li>1 Cup of Spinach</li>
</ul>
{% endblock %}

{% block recipe_steps %}
<h2>Recipe Steps</h2>
<ol>
    <li>In a measuring cup or bowl, add the eggs with the salt and pepper; mix thoroughly</li>
    <li>Dice the bell pepper into small pieces</li>
    <li>Heat a non-stick frying pan on medium heat</li>
    <li>Add the bell peppers to saute them for 3 minutes</li>
    <li>Add the spinach to wilt it in the frying pan</li>
    <li>Remove the veggies from the frying pan to a plate or cutting board</li>
    <li>Reduce the heat on the frying pan to between medium and low</li>
    <li>Spray the frying pan with the canola oil</li>
    <li>Add the eggs to the frying pan</li>
    <li>While the eggs are still runny, add back the bell peppers and spinach</li>
    <li>Once the eggs are no longer runny, fold the eggs in half to form the omelette shape</li>
    <li>Cook until the bottom of the omelette has a slight bit of brown color</li>
    <li>Serve with your favorite toppings (salsa, ketchup)!</li>
</ol>
{% endblock %}

project/books/templates/books/smoothies.html
{% extends "base.html" %}

{% block content %}
<div class="recipe-container">

    <div class="card">
        <a href="{{ url_for('books.smoothies_recipe', book_name='berry_smoothie') }}">
            <img
              src="{{ url_for('static', filename='img/berry_smoothie.jpg') }}"
              alt="Berry Smoothie"
              class="card__image" />
            <div class="card__body">
                <h2>Berry Smoothie</h2>
                <p class="recipe-badge dairy-free-badge">Dairy-Free</p>
                <p class="recipe-badge soy-free-badge">Soy-Free</p>
            </div>
        </a>
    </div>

    <div class="card">
        <a href="{{ url_for('books.smoothies_recipe', book_name='chocolate_milk_shake') }}">
            <img
              src="{{ url_for('static', filename='img/chocolate_milk_shake.jpg') }}"
              alt="Chocolate Milk Shake"
              class="card__image" />
            <div class="card__body">
                <h2 class="recipe-title-long">Chocolate Milk Shake</h2>
                <p class="recipe-badge dairy-free-badge">Dairy-Free</p>
                <p class="recipe-badge soy-free-badge">Soy-Free</p>
            </div>
        </a>
    </div>

</div>
{% endblock %}

project/books/templates/books/torah.html
{% extends "base.html" %}

{% block content %}
<h1 class="section-title">The Torah</h1>
<div class="recipe-container">

    <div class="card">
        <a href="{{ url_for('books.torah_book', book_name='Genesis') }}">
            <img
              src="{{ url_for('static', filename='img/Genesis.jpg') }}"
              alt="Genesis"
              class="card__image" />
            <div class="card__body">
                <h2>Genesis</h2>
                <p class="recipe-badge dairy-free-badge">Bereshit</p>
                <p class="recipe-badge soy-free-badge">50 Chapters</p>
            </div>
        </a>
    </div>

    <div class="card">
        <a href="{{ url_for('books.torah_book', book_name='Exodus') }}">
            <img
              src="{{ url_for('static', filename='img/Exodus.jpg') }}"
              alt="Exodus"
              class="card__image" />
            <div class="card__body">
                <h2 class="recipe-title-long">Exodus</h2>
                <p class="recipe-badge dairy-free-badge">Shemot</p>
                <p class="recipe-badge soy-free-badge">40 Chapters</p>
            </div>
        </a>
    </div>

    <div class="card">
        <a href="{{ url_for('books.torah_book', book_name='Leviticus') }}">
            <img
              src="{{ url_for('static', filename='img/Leviticus.jpg') }}"
              alt="Leviticus"
              class="card__image" />
            <div class="card__body">
                <h2>Leviticus</h2>
                <p class="recipe-badge dairy-free-badge">Wayiqra</p>
                <p class="recipe-badge soy-free-badge">27 Chapters</p>
            </div>
        </a>
    </div>

    <div class="card">
        <a href="{{ url_for('books.torah_book', book_name='Numbers') }}">
            <img
              src="{{ url_for('static', filename='img/Numbers.jpg') }}"
              alt="Numbers"
              class="card__image" />
            <div class="card__body">
                <h2 class="recipe-title-long">Numbers</h2>
                <p class="recipe-badge dairy-free-badge">Bemidbar</p>
                <p class="recipe-badge soy-free-badge">36 Chapters</p>
            </div>
        </a>
    </div>

    <div class="card">
        <a href="{{ url_for('books.torah_book', book_name='Deuteronomy') }}">
            <img
              src="{{ url_for('static', filename='img/Deuteronomy.jpg') }}"
              alt="Deuteronomy"
              class="card__image" />
            <div class="card__body">
                <h2>Deuteronomy</h2>
                <p class="recipe-badge dairy-free-badge">Devarim</p>
                <p class="recipe-badge soy-free-badge">34 Chapters</p>
            </div>
        </a>
    </div>


</div>
{% endblock %}